"""Chapter and verse counts per book (KJV versification; the local NKJV and 개역한글 data match it).

Generated by scripts/gen_versification.py. Contains numbers only.
"""

from __future__ import annotations

import json
from functools import cache
from pathlib import Path

_PATH = Path(__file__).with_name("versification.json")


@cache
def _counts() -> dict[str, list[int]]:
    return json.loads(_PATH.read_text(encoding="utf-8"))


def chapter_count(book: str) -> int:
    return len(_counts().get(book, []))


def verse_count(book: str, chapter: int) -> int | None:
    chapters = _counts().get(book, [])
    if 1 <= chapter <= len(chapters):
        return chapters[chapter - 1]
    return None


def books() -> list[str]:
    return list(_counts())
